### ISSUE TITLE
Compile multiple *.ahk script, but lost one

### ISSUE THREAD

**Issue by Jvcon** [nukdokplex/autohotkey-build#2]
There is "EhAria2.ahk", "EhAria2Extension.ahk" and "EhAria2Torrent.ahk" in directory, but it always failed to compile "EhAria2.exe", "EhAria2Extension.exe" and "EhAria2Torrent.exe".

Here is my workflow yaml 
```yml
name: Compile

on:
  push:
    branches: 
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build with AHK v2
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          version: v2.0.2
          x64: true
          x64_suffix: ""
          compression: upx
          in: ""
          out: build
      - name: Do Something with builded scripts
        shell: pwsh
        run: |
          ls build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
            name: my-artifact
            path: ${{ github.workspace }}
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/EhAria2.exe
            build/EhAria2Extension.exe
            build/EhAria2Torrent.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

Here is my Workflow log : [Jvcon/EhAria2/actions](https://github.com/Jvcon/EhAria2/actions)
