### ISSUE TITLE
No .exe file generated with AutoHotkey v2.0.4

### ISSUE THREAD

**Issue by Timtam** [nukdokplex/autohotkey-build#4]
Hi there,

I tried to use your action the following way:

```
on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with AHK v2.0.4
        uses: nukdokplex/autohotkey-build@v1
        with:
          version: v2.0.4
          x64: false
          x86: true
          x86_suffix: ""
          compression: none
          in: ReaHotkey.ahk
          out: ""
      - 
        name: "Build artifact"
        run: 7z a ReaHotkey.zip ReaHotkey.exe Images nvdaControllerClient32.dll
      - 
        name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "ReaHotkey"
          path: ReaHotkey.zip
```

The result is a success message from your script, but no .exe file being there. I don't get any helpful AHK2EXE output either. Do you know what might be wrong / what I could check?
